name       : gtef
version    : 2.0.1
release    : 2
source     :
    - https://download.gnome.org/sources/gtef/2.0/gtef-2.0.1.tar.xz : 8432f0f404b93e5a2702978b5f121b8f9ae2167c906e9f2ed7b5165142e27a4f
license    : LGPL-2.1
component  : programming.library
summary    : Gtef is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Gtef is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(uchardet)
    - gvfs-devel
    - vala
    - valgrind
setup      : |
    %configure --enable-gvfs-metadata
build      : |
    %make
install    : |
    %make_install -j1
